#!/usr/bin/env python3
"""Coverage-aware DETR: predicts frontier position + normalised opinion increase.

Trained from the coverage dataset (step_{fid}.json files) generated by the
geometric pipeline.  Adds a score head that predicts the normalised opinion
increase (marginal_gain / total_marginal_gain from greedy selection) for each
frontier candidate.

Usage:
    python models/coverage_detr_model.py prepare \
        --coverage-dir results/coverage_dataset \
        --out cov_detr_cache --min-id 29 --max-id 5000
    python models/coverage_detr_model.py train \
        --data cov_detr_cache --save-dir cov_detr_checkpoints \
        --epochs 200 --batch-size 32 --lr 1e-4 \
        --split-id 1500 --lambda-score 2.0
    python models/coverage_detr_model.py predict \
        --frontier-id 7000 --checkpoint cov_detr_cache/model_best.pt \
        --coverage-dir results/coverage_dataset
"""

import argparse
import json
import math
import os
import sys
import time

import numpy as np

# Reuse path constants and loader from map_utils
_this_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _this_dir)                    # for map_utils
sys.path.insert(0, os.path.dirname(_this_dir))   # for models.*
from map_utils import load_frontier_data, BASE_DIR, DUMP_DIR, FRONTIERS_DIR

# Reuse grid building and BEV construction from frontier_gain_model
from models.frontier_gain_model import (
    build_sample, build_atlas_grid, build_coverage_grid,
    get_current_map_mask, load_atlas,
    RESOLUTION, GRID_SIZE, HALF_EXTENT,
)

# Reuse coordinate conversions and visualisation from frontier_detr_model
from models.frontier_detr_model import (
    world_to_bev_normalized, bev_normalized_to_world, _bev_vis,
    BEV_EXTENT, MAX_QUERIES, compute_detr_metrics,
)

# ── Loss constants ───────────────────────────────────────────────────────
LAMBDA_L1 = 5.0
LAMBDA_CONF = 1.0
LAMBDA_SCORE = 2.0


# ── Prepare (pre-compute dataset) ──────────────────────────────────────
def cmd_prepare(args):
    out_dir = args.out
    os.makedirs(out_dir, exist_ok=True)

    print("Loading atlas ...")
    atlas_pts, wp_positions, g2c = load_atlas()
    atlas_cat, gx_min, gy_min = build_atlas_grid(g2c)
    atlas_gmin = (gx_min, gy_min)
    print(f"  {len(atlas_pts):,} atlas points, {len(wp_positions)} waypoints"
          f", atlas grid {atlas_cat.shape}")

    # Discover step files (manifest.json optional)
    coverage_dir = args.coverage_dir
    manifest_path = os.path.join(coverage_dir, 'manifest.json')
    if os.path.exists(manifest_path):
        with open(manifest_path) as f:
            manifest = json.load(f)
        fids = sorted(manifest['frontier_ids'])
    else:
        # Scan for step_*.json files directly
        fids = sorted(
            int(f.split('_')[1].split('.')[0])
            for f in os.listdir(coverage_dir)
            if f.startswith('step_') and f.endswith('.json')
        )
    if args.min_id is not None:
        fids = [f for f in fids if f >= args.min_id]
    if args.max_id is not None:
        fids = [f for f in fids if f <= args.max_id]
    print(f"  {len(fids)} steps (id range: {fids[0]}–{fids[-1]})")

    meta_list = []
    t0 = time.time()

    for fi, fid in enumerate(fids):
        step_path = os.path.join(coverage_dir, f'step_{fid}.json')
        if not os.path.exists(step_path):
            continue
        with open(step_path) as f:
            step_data = json.load(f)

        wids = step_data['waypoint_ids']
        candidates = step_data.get('candidates', [])

        if len(wids) == 0:
            continue

        # Shared coverage grid for all WPs in this step
        cmask = get_current_map_mask(wids, wp_positions, atlas_pts)
        atlas_cov = build_coverage_grid(atlas_pts, cmask,
                                        gx_min, gy_min, atlas_cat.shape)

        # Build candidate_idx → marginal_gain from selection_order
        selection_order = step_data.get('selection_order', [])
        cand_marginal = {}
        for sel in selection_order:
            cand_marginal[sel['candidate_idx']] = sel['marginal_gain']
        total_mg = sum(cand_marginal.values())

        # Attach normalised opinion increase to each candidate
        for ci, cand in enumerate(candidates):
            mg = cand_marginal.get(ci, 0)
            cand['_norm_opinion'] = mg / total_mg if total_mg > 0 else 0.0

        # Group candidates by wp_id
        wp_to_cands = {}
        for cand in candidates:
            wp_to_cands.setdefault(cand['wp_id'], []).append(cand)

        # Process each WP as one training sample
        for wp_id in wids:
            if wp_id not in wp_positions:
                continue

            wp_pos = wp_positions[wp_id]
            center_xy = np.array([wp_pos[0], wp_pos[1]])

            # Random rotation for data augmentation
            theta = np.random.uniform(0, 2 * np.pi)

            # Build 8-channel BEV centered on this WP
            inp, _ = build_sample(center_xy, theta,
                                  atlas_cat, atlas_cov, atlas_gmin,
                                  obs_wp_id=wp_id)

            # Candidates for this WP
            cands = wp_to_cands.get(wp_id, [])
            if cands:
                cand_xy = np.array([[c['x'], c['y']] for c in cands])
                cand_scores = np.array([c['_norm_opinion'] for c in cands],
                                       dtype=np.float32)
                targets_norm = world_to_bev_normalized(cand_xy, center_xy,
                                                       theta)

                # Keep only targets within [0, 1]²
                valid = ((targets_norm[:, 0] >= 0) &
                         (targets_norm[:, 0] <= 1) &
                         (targets_norm[:, 1] >= 0) &
                         (targets_norm[:, 1] <= 1))
                targets_norm = targets_norm[valid].astype(np.float32)
                cand_scores = cand_scores[valid]
            else:
                targets_norm = np.empty((0, 2), dtype=np.float32)
                cand_scores = np.empty((0,), dtype=np.float32)

            n_targets = len(targets_norm)

            fname = f"{fid}_{wp_id}.npz"
            np.savez_compressed(
                os.path.join(out_dir, fname),
                input=inp.astype(np.float16),
                targets=targets_norm,
                scores=cand_scores,
                n_targets=np.int32(n_targets))

            meta_list.append({
                'file': fname,
                'frontier_id': fid,
                'wp_id': wp_id,
                'n_targets': n_targets,
            })

        if (fi + 1) % 50 == 0 or fi == len(fids) - 1:
            elapsed = time.time() - t0
            print(f"  [{fi+1}/{len(fids)}] {len(meta_list)} samples  "
                  f"({elapsed:.1f}s)")

    with open(os.path.join(out_dir, 'meta.json'), 'w') as f:
        json.dump(meta_list, f)

    n_pos = sum(1 for m in meta_list if m['n_targets'] > 0)
    n_neg = sum(1 for m in meta_list if m['n_targets'] == 0)
    print(f"\nDone: {len(meta_list)} samples saved to {out_dir}/")
    print(f"  Positive (has candidates): {n_pos}")
    print(f"  Negative (no candidates): {n_neg}")


# ── PyTorch imports (deferred so prepare works without torch) ───────────
def _import_torch():
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    return torch, nn, F


def _get_device():
    torch, _, _ = _import_torch()
    if torch.cuda.is_available():
        return torch.device('cuda')
    return torch.device('cpu')


# ── Dataset ──────────────────────────────────────────────────────────────
class CoverageDETRDataset:
    """Lazy-loading dataset for coverage DETR training.

    Returns (inp, targets_xy, targets_score, n_targets).
    Train/val split by frontier_id.  Supports --min-id/--max-id filtering.
    """

    def __init__(self, cache_dir, split='train', split_id=1500,
                 min_id=None, max_id=None):
        torch, _, _ = _import_torch()
        with open(os.path.join(cache_dir, 'meta.json')) as f:
            all_meta = json.load(f)

        # Filter by frontier_id range first
        if min_id is not None:
            all_meta = [m for m in all_meta if m['frontier_id'] >= min_id]
        if max_id is not None:
            all_meta = [m for m in all_meta if m['frontier_id'] <= max_id]

        # Then split
        if split == 'train':
            self.meta = [m for m in all_meta if m['frontier_id'] < split_id]
        elif split == 'val':
            self.meta = [m for m in all_meta if m['frontier_id'] >= split_id]
        else:
            self.meta = list(all_meta)

        self.cache_dir = cache_dir
        self.torch = torch

    def __len__(self):
        return len(self.meta)

    def __getitem__(self, idx):
        m = self.meta[idx]
        data = np.load(os.path.join(self.cache_dir, m['file']))
        inp = data['input'].astype(np.float32)          # (8, 100, 100)
        targets = data['targets'].astype(np.float32)    # (K, 2)
        scores = data['scores'].astype(np.float32)      # (K,)
        n_targets = int(data['n_targets'])

        # Pad targets and scores to MAX_QUERIES
        padded_xy = np.zeros((MAX_QUERIES, 2), dtype=np.float32)
        padded_sc = np.zeros((MAX_QUERIES,), dtype=np.float32)
        n = min(n_targets, MAX_QUERIES)
        if n > 0:
            padded_xy[:n] = targets[:n]
            padded_sc[:n] = scores[:n]

        return (self.torch.from_numpy(inp),
                self.torch.from_numpy(padded_xy),
                self.torch.from_numpy(padded_sc),
                n)


# ── Model ────────────────────────────────────────────────────────────────
def _build_coverage_detr():
    torch, nn, F = _import_torch()

    class DoubleConv(nn.Module):
        def __init__(self, in_ch, out_ch):
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 3, padding=1),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
                nn.Conv2d(out_ch, out_ch, 3, padding=1),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=True),
            )

        def forward(self, x):
            return self.net(x)

    class PositionalEncoding2D(nn.Module):
        """Fixed 2D sinusoidal positional encoding for spatial feature maps."""

        def __init__(self, d_model, h, w):
            super().__init__()
            pe = torch.zeros(d_model, h, w)
            half = d_model // 2
            pos_h = torch.arange(h).unsqueeze(1).float()
            div = torch.exp(torch.arange(0, half, 2).float()
                            * -(math.log(10000.0) / half))
            pe[0:half:2, :, :] = torch.sin(
                pos_h * div.unsqueeze(0)).T.unsqueeze(2).expand(-1, -1, w)
            pe[1:half:2, :, :] = torch.cos(
                pos_h * div.unsqueeze(0)).T.unsqueeze(2).expand(-1, -1, w)
            pos_w = torch.arange(w).unsqueeze(1).float()
            pe[half::2, :, :] = torch.sin(
                pos_w * div.unsqueeze(0)).T.unsqueeze(1).expand(-1, h, -1)
            pe[half + 1::2, :, :] = torch.cos(
                pos_w * div.unsqueeze(0)).T.unsqueeze(1).expand(-1, h, -1)
            self.register_buffer('pe', pe)

        def forward(self, x):
            return x + self.pe.unsqueeze(0)

    class CoverageDETR(nn.Module):
        def __init__(self, d_model=256, nhead=8, num_encoder_layers=3,
                     num_decoder_layers=3, num_queries=MAX_QUERIES):
            super().__init__()
            self.d_model = d_model
            self.num_queries = num_queries

            # CNN backbone (UNet encoder)
            self.enc1 = DoubleConv(8, 32)
            self.enc2 = DoubleConv(32, 64)
            self.enc3 = DoubleConv(64, 128)
            self.enc4 = DoubleConv(128, d_model)
            self.pool = nn.MaxPool2d(2)

            # 2D positional encoding for 12×12 feature map
            self.pos_enc = PositionalEncoding2D(d_model, 12, 12)

            # Transformer
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=d_model, nhead=nhead,
                dim_feedforward=d_model * 4,
                dropout=0.1, batch_first=False)
            self.transformer_encoder = nn.TransformerEncoder(
                encoder_layer, num_layers=num_encoder_layers)

            decoder_layer = nn.TransformerDecoderLayer(
                d_model=d_model, nhead=nhead,
                dim_feedforward=d_model * 4,
                dropout=0.1, batch_first=False)
            self.transformer_decoder = nn.TransformerDecoder(
                decoder_layer, num_layers=num_decoder_layers)

            # Learned object queries
            self.query_embed = nn.Parameter(
                torch.randn(num_queries, d_model) * 0.02)

            # Prediction heads
            self.xy_head = nn.Sequential(
                nn.Linear(d_model, d_model),
                nn.ReLU(inplace=True),
                nn.Linear(d_model, 2),
            )
            self.conf_head = nn.Sequential(
                nn.Linear(d_model, d_model),
                nn.ReLU(inplace=True),
                nn.Linear(d_model, 1),
            )
            # Score head: outputs logits; softmax over queries at loss/inference
            # to produce normalised opinion increase predictions
            self.score_head = nn.Sequential(
                nn.Linear(d_model, d_model),
                nn.ReLU(inplace=True),
                nn.Linear(d_model, 1),
            )

        def forward(self, x):
            """
            Args:
                x: (B, 8, 100, 100) BEV input
            Returns:
                pred_xy:    (B, Q, 2) normalized [0,1]² coordinates
                pred_conf:  (B, Q) confidence logits
                pred_score: (B, Q) score logits (softmax → norm. opinion)
            """
            B = x.size(0)

            # CNN backbone
            e1 = self.enc1(x)
            e2 = self.enc2(self.pool(e1))
            e3 = self.enc3(self.pool(e2))
            e4 = self.enc4(self.pool(e3))

            # Add positional encoding
            e4 = self.pos_enc(e4)

            # Flatten spatial dims → sequence: (144, B, 256)
            feat = e4.flatten(2).permute(2, 0, 1)

            # Transformer encoder
            memory = self.transformer_encoder(feat)

            # Transformer decoder with object queries
            queries = self.query_embed.unsqueeze(1).expand(-1, B, -1)
            hs = self.transformer_decoder(queries, memory)

            # Prediction heads
            hs = hs.permute(1, 0, 2)                    # (B, Q, 256)
            pred_xy = torch.sigmoid(self.xy_head(hs))    # (B, Q, 2)
            pred_conf = self.conf_head(hs).squeeze(-1)   # (B, Q)
            pred_score = self.score_head(hs).squeeze(-1)  # (B, Q)

            return pred_xy, pred_conf, pred_score

    return CoverageDETR


# ── Hungarian matching loss with score ──────────────────────────────────
def hungarian_loss_with_score(pred_xy, pred_conf, pred_score,
                              target_xy, target_score, n_targets,
                              lambda_l1=LAMBDA_L1,
                              lambda_conf=LAMBDA_CONF,
                              lambda_score=LAMBDA_SCORE):
    """Compute Hungarian matching loss with normalised opinion increase.

    Matching cost uses only position + confidence (score is NOT in matching).
    After matching:
      - L1 position loss is weighted by GT normalised opinion per matched pair
      - Score loss: MSE between softmax(pred_score) and GT normalised opinion
        across ALL queries (unmatched queries target 0)

    Args:
        pred_xy      : (B, Q, 2) predicted normalized coordinates
        pred_conf    : (B, Q) confidence logits
        pred_score   : (B, Q) score logits
        target_xy    : (B, Q, 2) padded target coordinates
        target_score : (B, Q) padded GT normalised opinion increase
        n_targets    : tensor/list of int, actual target count per sample

    Returns:
        total_loss, loss_dict
    """
    torch, _, F = _import_torch()
    from scipy.optimize import linear_sum_assignment

    B, Q, _ = pred_xy.shape
    device = pred_xy.device

    total_l1 = torch.tensor(0.0, device=device)
    total_conf = torch.tensor(0.0, device=device)
    total_score = torch.tensor(0.0, device=device)
    n_matched = 0

    for b in range(B):
        nt = int(n_targets[b]) if not isinstance(n_targets, int) else n_targets
        nt = min(nt, Q)

        # Softmax over all queries → normalised predicted scores
        pred_score_norm = F.softmax(pred_score[b], dim=0)  # (Q,)

        if nt == 0:
            # All queries should predict "no frontier"
            total_conf = total_conf + F.binary_cross_entropy_with_logits(
                pred_conf[b],
                torch.zeros(Q, device=device),
                reduction='sum')
            # Score: all targets are 0, uniform softmax is the target
            score_target = torch.zeros(Q, device=device)
            total_score = total_score + F.mse_loss(
                pred_score_norm, score_target, reduction='sum')
            continue

        gt = target_xy[b, :nt]
        pred = pred_xy[b]

        # Cost matrix (position + confidence only — NOT score)
        l1_cost = torch.cdist(pred.unsqueeze(0),
                              gt.unsqueeze(0), p=1).squeeze(0)
        conf_prob = torch.sigmoid(pred_conf[b])
        conf_cost = -torch.log(conf_prob + 1e-8).unsqueeze(1).expand(-1, nt)

        cost = lambda_l1 * l1_cost + lambda_conf * conf_cost
        cost_np = cost.detach().cpu().numpy()
        row_ind, col_ind = linear_sum_assignment(cost_np)

        # GT normalised opinion for matched targets
        gt_opinions = target_score[b, :nt][col_ind]  # (n_matched,)

        # Matched pairs: L1 position loss weighted by GT normalised opinion
        per_pair_l1 = torch.sum(
            torch.abs(pred[row_ind] - gt[col_ind]), dim=1)  # (n_matched,)
        total_l1 = total_l1 + torch.sum(per_pair_l1 * gt_opinions)

        # Confidence targets: 1 for matched, 0 for unmatched
        conf_target = torch.zeros(Q, device=device)
        conf_target[row_ind] = 1.0
        total_conf = total_conf + F.binary_cross_entropy_with_logits(
            pred_conf[b], conf_target, reduction='sum')

        # Score loss: MSE(softmax(pred), GT norm opinion) over all queries
        score_target = torch.zeros(Q, device=device)
        score_target[row_ind] = gt_opinions
        total_score = total_score + F.mse_loss(
            pred_score_norm, score_target, reduction='sum')

        n_matched += nt

    # Normalise
    n_total = max(n_matched, 1)
    loss_l1 = lambda_l1 * total_l1 / n_total
    loss_conf = lambda_conf * total_conf / B
    loss_score = lambda_score * total_score / B
    total_loss = loss_l1 + loss_conf + loss_score

    return total_loss, {
        'loss_l1': loss_l1.item(),
        'loss_conf': loss_conf.item(),
        'loss_score': loss_score.item(),
        'loss_total': total_loss.item(),
        'n_matched': n_matched,
    }


# ── Metrics (extends existing with score MSE) ──────────────────────────
def compute_coverage_metrics(pred_xy, pred_conf, pred_score,
                             target_xy, target_score, n_targets,
                             conf_thresh=0.5,
                             dist_thresholds_m=(0.5, 1.0)):
    """Compute AP metrics plus score MSE on matched pairs.

    pred_score are logits; softmax is applied here for evaluation.
    target_score are GT normalised opinion values.
    """
    torch, _, F = _import_torch()
    from scipy.optimize import linear_sum_assignment

    B = pred_xy.shape[0]

    n_gt_total = 0
    n_pred_total = 0
    n_tp = {d: 0 for d in dist_thresholds_m}
    l1_sum_m = 0.0
    l1_count = 0
    score_se_sum = 0.0
    score_se_count = 0

    for b in range(B):
        nt = min(int(n_targets[b]), pred_xy.shape[1])
        conf = torch.sigmoid(pred_conf[b])
        mask = conf > conf_thresh
        n_pred = int(mask.sum().item())
        n_pred_total += n_pred

        if nt == 0:
            continue
        n_gt_total += nt

        if n_pred == 0:
            continue

        gt = target_xy[b, :nt]
        pred = pred_xy[b][mask]

        # Softmax over ALL queries, then index the confident ones
        pred_score_norm = F.softmax(pred_score[b], dim=0)

        # Distance matrix in metres
        dist_m = torch.cdist(
            pred.unsqueeze(0), gt.unsqueeze(0), p=2
        ).squeeze(0) * BEV_EXTENT

        min_dist, _ = dist_m.min(dim=0)
        for d in dist_thresholds_m:
            n_tp[d] += int((min_dist < d).sum().item())

        # Hungarian for mean L1 and score MSE
        cost_np = dist_m.detach().cpu().numpy()
        if cost_np.shape[0] > 0 and cost_np.shape[1] > 0:
            ri, ci = linear_sum_assignment(cost_np)
            # Map ri (indices into masked pred) back to full query indices
            mask_indices = torch.where(mask)[0]
            for r, c in zip(ri, ci):
                l1_sum_m += cost_np[r, c]
                l1_count += 1
                p_sc = float(pred_score_norm[mask_indices[r]].item())
                g_sc = float(target_score[b, c].item())
                score_se_sum += (p_sc - g_sc) ** 2
                score_se_count += 1

    metrics = {}
    for d in dist_thresholds_m:
        metrics[f'ap_{d}m'] = n_tp[d] / max(n_gt_total, 1)
    metrics['precision'] = (n_tp[1.0] / max(n_pred_total, 1)
                            if 1.0 in n_tp else 0.0)
    metrics['recall'] = (n_tp[1.0] / max(n_gt_total, 1)
                         if 1.0 in n_tp else 0.0)
    metrics['mean_l1_m'] = l1_sum_m / max(l1_count, 1)
    metrics['score_mse'] = score_se_sum / max(score_se_count, 1)
    metrics['n_gt'] = n_gt_total
    metrics['n_pred'] = n_pred_total
    return metrics


# ── Training ─────────────────────────────────────────────────────────────
def cmd_train(args):
    torch, nn, _ = _import_torch()
    from torch.utils.data import DataLoader

    device = _get_device()
    print(f"Device: {device}")

    train_ds = CoverageDETRDataset(args.data, 'train', args.split_id,
                                   args.min_id, args.max_id)
    val_ds = CoverageDETRDataset(args.data, 'val', args.split_id,
                                 args.min_id, args.max_id)
    print(f"Train: {len(train_ds)},  Val: {len(val_ds)}")

    if len(train_ds) == 0 or len(val_ds) == 0:
        print("ERROR: Empty train or val set. Check data, split_id, "
              "and min/max-id.")
        return

    def collate_fn(batch):
        inps, tgt_xy, tgt_sc, n_tgts = zip(*batch)
        return (torch.stack(inps),
                torch.stack(tgt_xy),
                torch.stack(tgt_sc),
                torch.tensor(n_tgts, dtype=torch.long))

    nw = 0 if sys.platform == 'darwin' else 4
    train_loader = DataLoader(train_ds, batch_size=args.batch_size,
                              shuffle=True, num_workers=nw, pin_memory=True,
                              collate_fn=collate_fn)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size,
                            shuffle=False, num_workers=nw, pin_memory=True,
                            collate_fn=collate_fn)

    CoverageDETR = _build_coverage_detr()
    model = CoverageDETR().to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model params: {n_params:,}")

    # Separate backbone and transformer params for different lr
    backbone_params = []
    other_params = []
    for name, param in model.named_parameters():
        if name.startswith(('enc1', 'enc2', 'enc3', 'enc4')):
            backbone_params.append(param)
        else:
            other_params.append(param)

    optimizer = torch.optim.AdamW([
        {'params': backbone_params, 'lr': args.lr * 0.1},
        {'params': other_params, 'lr': args.lr},
    ], weight_decay=args.weight_decay)

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs)

    save_dir = args.save_dir if args.save_dir else args.data
    os.makedirs(save_dir, exist_ok=True)

    best_val_ap = 0.0

    for epoch in range(1, args.epochs + 1):
        # ── Train ──
        model.train()
        train_loss = 0.0
        train_n = 0
        n_batches = len(train_loader)
        for step_i, (inp, tgt_xy, tgt_sc, n_tgts) in enumerate(
                train_loader, 1):
            inp = inp.to(device)
            tgt_xy = tgt_xy.to(device)
            tgt_sc = tgt_sc.to(device)

            pred_xy, pred_conf, pred_score = model(inp)
            loss, ldict = hungarian_loss_with_score(
                pred_xy, pred_conf, pred_score,
                tgt_xy, tgt_sc, n_tgts,
                lambda_score=args.lambda_score)

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
            optimizer.step()

            train_loss += loss.item() * inp.size(0)
            train_n += inp.size(0)

            print(f"  E{epoch} [{step_i}/{n_batches}]  "
                  f"loss={ldict['loss_total']:.4f}  "
                  f"L1={ldict['loss_l1']:.4f}  "
                  f"conf={ldict['loss_conf']:.4f}  "
                  f"score={ldict['loss_score']:.6f}", flush=True)
        train_loss /= max(train_n, 1)

        # ── Validate ──
        model.eval()
        val_loss = 0.0
        val_n = 0
        all_pred_xy, all_pred_conf, all_pred_score = [], [], []
        all_tgt_xy, all_tgt_sc, all_n_targets = [], [], []

        with torch.no_grad():
            for inp, tgt_xy, tgt_sc, n_tgts in val_loader:
                inp = inp.to(device)
                tgt_xy = tgt_xy.to(device)
                tgt_sc = tgt_sc.to(device)

                pred_xy, pred_conf, pred_score = model(inp)
                loss, _ = hungarian_loss_with_score(
                    pred_xy, pred_conf, pred_score,
                    tgt_xy, tgt_sc, n_tgts,
                    lambda_score=args.lambda_score)
                val_loss += loss.item() * inp.size(0)
                val_n += inp.size(0)

                all_pred_xy.append(pred_xy.cpu())
                all_pred_conf.append(pred_conf.cpu())
                all_pred_score.append(pred_score.cpu())
                all_tgt_xy.append(tgt_xy.cpu())
                all_tgt_sc.append(tgt_sc.cpu())
                all_n_targets.append(n_tgts)

        val_loss /= max(val_n, 1)

        # Compute metrics on full val set
        vm = compute_coverage_metrics(
            torch.cat(all_pred_xy), torch.cat(all_pred_conf),
            torch.cat(all_pred_score),
            torch.cat(all_tgt_xy), torch.cat(all_tgt_sc),
            torch.cat(all_n_targets))

        scheduler.step()
        lr = optimizer.param_groups[1]['lr']

        ap1 = vm['ap_1.0m']
        print(f"Epoch {epoch:3d}/{args.epochs}  "
              f"tl={train_loss:.4f}  vl={val_loss:.4f}  "
              f"AP@0.5={vm['ap_0.5m']:.4f}  AP@1.0={ap1:.4f}  "
              f"P={vm['precision']:.4f}  R={vm['recall']:.4f}  "
              f"L1={vm['mean_l1_m']:.2f}m  "
              f"sMSE={vm['score_mse']:.6f}  lr={lr:.2e}")

        if ap1 > best_val_ap:
            best_val_ap = ap1
            torch.save(model.state_dict(),
                       os.path.join(save_dir, 'model_best.pt'))
            print(f"  -> saved best (AP@1.0m={best_val_ap:.4f})")

        if epoch % args.save_every == 0:
            torch.save(model.state_dict(),
                       os.path.join(save_dir, f'model_epoch{epoch}.pt'))

    torch.save(model.state_dict(), os.path.join(save_dir, 'model_final.pt'))
    print(f"\nDone. Best val AP@1.0m: {best_val_ap:.4f}")


# ── Predict / Visualise ─────────────────────────────────────────────────
def cmd_predict(args):
    torch, _, _ = _import_torch()
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    device = _get_device()

    CoverageDETR = _build_coverage_detr()
    model = CoverageDETR().to(device)
    model.load_state_dict(
        torch.load(args.checkpoint, map_location=device, weights_only=True))
    model.eval()

    atlas_pts, wp_positions, g2c = load_atlas()
    atlas_cat, gx_min, gy_min = build_atlas_grid(g2c)
    atlas_gmin = (gx_min, gy_min)

    fid = args.frontier_id

    # Load frontier data for WP list and coverage grid
    fdata = load_frontier_data(fid)
    wids = fdata['waypoint_ids']

    cmask = get_current_map_mask(wids, wp_positions, atlas_pts)
    atlas_cov = build_coverage_grid(atlas_pts, cmask,
                                    gx_min, gy_min, atlas_cat.shape)

    # Load GT from coverage dataset if available
    gt_candidates = None
    wp_to_gt = {}
    if args.coverage_dir:
        step_path = os.path.join(args.coverage_dir, f'step_{fid}.json')
        if os.path.exists(step_path):
            with open(step_path) as f:
                step_data = json.load(f)
            gt_candidates = step_data.get('candidates', [])
            for cand in gt_candidates:
                wp_to_gt.setdefault(cand['wp_id'], []).append(cand)
            print(f"Loaded {len(gt_candidates)} GT candidates from "
                  f"coverage dataset")
        else:
            print(f"No coverage data for frontier {fid}, running without GT")

    results_dir = os.path.join(os.path.dirname(BASE_DIR), 'results')
    out_dir = os.path.join(results_dir, f"predict_cov_detr_{fid}")
    os.makedirs(out_dir, exist_ok=True)

    conf_thresh = 0.3
    coverage_rate = args.coverage_rate

    # Collect all predictions and GT in world coords (for summary map)
    all_pred_world = []    # [(x, y, conf, norm_score), ...]
    all_gt_world = []      # [(x, y, norm_opinion), ...]

    # Build GT normalised opinion from selection_order if available
    gt_norm_opinion = {}  # candidate_idx → normalised opinion
    if args.coverage_dir:
        step_path2 = os.path.join(args.coverage_dir, f'step_{fid}.json')
        if os.path.exists(step_path2):
            with open(step_path2) as f:
                step_data2 = json.load(f)
            sel_order = step_data2.get('selection_order', [])
            cand_mg = {s['candidate_idx']: s['marginal_gain']
                       for s in sel_order}
            total_mg = sum(cand_mg.values())
            if total_mg > 0:
                for ci, cand in enumerate(
                        step_data2.get('candidates', [])):
                    mg = cand_mg.get(ci, 0)
                    cand['_norm_opinion'] = mg / total_mg

    print(f"Frontier {fid}: {len(wids)} WPs")
    if gt_candidates is not None:
        print(f"  GT candidates: {len(gt_candidates)}")
    print(f"{'WP':>6}  {'#GT':>4}  {'#Pred':>5}  "
          f"Predictions (row,col,conf,score)")
    print("-" * 80)

    # ── Build all BEV inputs first ───────────────────────────────────
    valid_wids = [w for w in wids if w in wp_positions]
    all_inps = []
    all_centers = []
    theta = 0.0  # no rotation at inference

    print(f"Building {len(valid_wids)} BEV grids ...")
    for wp_id in valid_wids:
        wp_pos = wp_positions[wp_id]
        center_xy = np.array([wp_pos[0], wp_pos[1]])
        inp, _ = build_sample(center_xy, theta,
                              atlas_cat, atlas_cov, atlas_gmin,
                              obs_wp_id=wp_id)
        all_inps.append(inp)
        all_centers.append(center_xy)

    # ── Batched model forward pass ───────────────────────────────────
    import torch.nn.functional as _F
    inp_batch = torch.from_numpy(np.stack(all_inps)).to(device)
    print(f"Running batched inference ({inp_batch.shape[0]} samples) ...")
    with torch.no_grad():
        pred_xy_all, pred_conf_all, pred_score_all = model(inp_batch)

    pred_xy_np = pred_xy_all.cpu().numpy()
    conf_np = torch.sigmoid(pred_conf_all).cpu().numpy()
    score_norm_np = _F.softmax(pred_score_all, dim=1).cpu().numpy()

    # ── Process results per WP ───────────────────────────────────────
    for wp_idx, wp_id in enumerate(valid_wids):
        center_xy = all_centers[wp_idx]
        inp = all_inps[wp_idx]

        pxy = pred_xy_np[wp_idx]
        cnf = conf_np[wp_idx]
        snm = score_norm_np[wp_idx]

        # WP weight: number of unobserved cells in BEV (channel 3)
        wp_weight = float((inp[3] > 0).sum())

        # Confidence-filtered predictions
        mask = cnf > conf_thresh
        preds_bev = pxy[mask]
        confs = cnf[mask]
        # Weight local scores by WP importance
        scores_weighted = snm[mask] * wp_weight

        # GT candidates for this WP
        gt_cands = wp_to_gt.get(wp_id, [])
        if gt_cands:
            gt_xy = np.array([[c['x'], c['y']] for c in gt_cands])
            gt_opinions = np.array(
                [c.get('_norm_opinion', 0.0) for c in gt_cands])
            gt_bev = world_to_bev_normalized(gt_xy, center_xy, theta)
        else:
            gt_xy = np.empty((0, 2))
            gt_opinions = np.empty((0,))
            gt_bev = np.empty((0, 2))

        # Convert predictions to world coords
        if len(preds_bev):
            world_xy = bev_normalized_to_world(preds_bev, center_xy, theta)
            for i in range(len(world_xy)):
                all_pred_world.append([world_xy[i, 0], world_xy[i, 1],
                                       confs[i], scores_weighted[i]])

        for i, xy in enumerate(gt_xy):
            g = gt_opinions[i] if i < len(gt_opinions) else 0.0
            all_gt_world.append([xy[0], xy[1], g])

        # Console summary
        pred_str = '  '.join(
            f'({r:.2f},{c:.2f},{conf:.2f},{sc:.1f})'
            for (r, c), conf, sc in zip(preds_bev, confs, scores_weighted)
        ) if len(preds_bev) else '—'
        print(f"{wp_id:>6}  {len(gt_cands):>4}  {len(preds_bev):>5}  "
              f"{pred_str}")

        # ── Per-WP BEV figure (3 panels) ──────────────────────────────
        if not args.no_wp_plots:
            vis = _bev_vis(inp)
            WC = GRID_SIZE // 2

            fig, axes = plt.subplots(1, 3, figsize=(15, 5))

            # Panel 0 – input + depth
            axes[0].imshow(vis)
            axes[0].scatter(WC, WC, c='orange', s=150, marker='*',
                            edgecolors='white', linewidths=1.5, zorder=5)
            n_hit = int((inp[4] > 0).sum())
            n_pass = int((inp[5] > 0).sum())
            axes[0].set_title(f'Input+Depth  hit={n_hit} pass={n_pass}')

            # Panel 1 – input + GT candidates (sized by norm opinion)
            axes[1].imshow(vis)
            axes[1].scatter(WC, WC, c='orange', s=150, marker='*',
                            edgecolors='white', linewidths=1.5, zorder=5)
            if len(gt_bev):
                gt_valid = ((gt_bev[:, 0] >= 0) & (gt_bev[:, 0] <= 1) &
                            (gt_bev[:, 1] >= 0) & (gt_bev[:, 1] <= 1))
                gv = gt_bev[gt_valid] * GRID_SIZE
                go = gt_opinions[gt_valid] if len(gt_opinions) else np.array([])
                gt_sizes = 40 + np.clip(go, 0, 1) * 300 if len(go) else 40
                axes[1].scatter(gv[:, 1], gv[:, 0], c='lime', s=gt_sizes,
                                marker='s', edgecolors='darkgreen',
                                linewidths=1.5, zorder=6)
            n_gt_label = len(gt_cands) if gt_candidates is not None else '?'
            axes[1].set_title(f'+ GT candidates ({n_gt_label})')

            # Panel 2 – input + predictions (sized by weighted score, annotated)
            axes[2].imshow(vis)
            axes[2].scatter(WC, WC, c='orange', s=150, marker='*',
                            edgecolors='white', linewidths=1.5, zorder=5)
            if len(preds_bev):
                pv = preds_bev * GRID_SIZE
                # Normalise weighted scores for sizing within this WP
                sw_max = scores_weighted.max() if scores_weighted.max() > 0 else 1
                pred_sizes = 40 + np.clip(scores_weighted / sw_max, 0, 1) * 300
                axes[2].scatter(pv[:, 1], pv[:, 0], c='red', s=pred_sizes,
                                marker='o', edgecolors='darkred',
                                linewidths=1, alpha=0.85, zorder=6)
                for k in range(len(preds_bev)):
                    axes[2].annotate(
                        f'{confs[k]:.2f}/{scores_weighted[k]:.1f}',
                        (pv[k, 1], pv[k, 0]),
                        textcoords='offset points', xytext=(4, 4),
                        fontsize=6, color='white')
            axes[2].set_title(
                f'+ Preds ({len(preds_bev)}, conf>{conf_thresh}, '
                f'wt={wp_weight:.0f})')

            for ax in axes:
                ax.set_xticks([])
                ax.set_yticks([])

            plt.suptitle(
                f'CovDETR — Frontier {fid} / WP {wp_id}  '
                f'(#{wp_idx+1}/{len(wids)})',
                fontsize=11)
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, f'WP_{wp_id}.png'),
                        dpi=120, bbox_inches='tight')
            plt.close()

    # ── Greedy selection by predicted score until coverage rate ─────
    proximity_disq_m = args.proximity_disq_m
    if coverage_rate is not None and all_pred_world:
        pred_arr_full = np.array(all_pred_world)  # (N, 4): x,y,conf,score
        # Re-normalise scores across all predictions so they sum to 1
        raw_scores = pred_arr_full[:, 3].copy()
        score_sum = raw_scores.sum()
        if score_sum > 0:
            norm_scores = raw_scores / score_sum
        else:
            norm_scores = raw_scores

        # Greedy selection with proximity disqualification
        disq_r2 = proximity_disq_m * proximity_disq_m
        remaining = set(range(len(pred_arr_full)))
        selected_idx = []
        cum_score = 0.0

        # Sort order for greedy picking
        order = np.argsort(-norm_scores)
        rank = np.empty(len(order), dtype=int)
        rank[order] = np.arange(len(order))

        while remaining and cum_score < coverage_rate:
            # Pick highest-scoring remaining candidate
            best = min(remaining, key=lambda i: rank[i])
            selected_idx.append(best)
            remaining.discard(best)
            cum_score += norm_scores[best]

            # Disqualify nearby remaining candidates
            bx, by = pred_arr_full[best, 0], pred_arr_full[best, 1]
            too_close = set()
            for i in remaining:
                dx = pred_arr_full[i, 0] - bx
                dy = pred_arr_full[i, 1] - by
                if dx * dx + dy * dy <= disq_r2:
                    too_close.add(i)
            remaining -= too_close

        # Update scores in output to normalised values
        pred_arr_full[:, 3] = norm_scores
        selected = pred_arr_full[selected_idx]

        print(f"\n── Greedy selection (coverage_rate={coverage_rate:.2f}, "
              f"proximity={proximity_disq_m:.1f}m) ──")
        print(f"  Selected {len(selected_idx)}/{len(pred_arr_full)} predictions")
        print(f"  Cumulative normalised score: {cum_score:.4f}")

        # Replace all_pred_world with selected subset for plotting
        all_pred_world_selected = selected.tolist()
    else:
        all_pred_world_selected = all_pred_world

    # ── Summary atlas map ────────────────────────────────────────────
    atlas_vis = np.ones((*atlas_cat.shape, 3), dtype=np.float32) * 0.94
    covered = atlas_cov.astype(bool)
    cat_colors = {
        0: np.array([0.2, 0.8, 0.2]),
        1: np.array([0.1, 0.1, 0.1]),
        2: np.array([0.7, 0.5, 0.9]),
        3: np.array([0.85, 0.85, 0.85]),
    }
    for cat_id, color in cat_colors.items():
        atlas_vis[(atlas_cat == cat_id) & covered] = color

    atlas_vis_T = atlas_vis.transpose(1, 0, 2)

    n_gx, n_gy = atlas_cat.shape
    extent = [gx_min * RESOLUTION,
              (gx_min + n_gx) * RESOLUTION,
              gy_min * RESOLUTION,
              (gy_min + n_gy) * RESOLUTION]

    fig, ax = plt.subplots(1, 1, figsize=(16, 10))
    ax.imshow(atlas_vis_T, extent=extent, origin='lower', aspect='equal')

    # WP positions
    wp_xy = np.array([[wp_positions[w][0], wp_positions[w][1]]
                      for w in wids if w in wp_positions])
    if len(wp_xy):
        ax.scatter(wp_xy[:, 0], wp_xy[:, 1], c='steelblue', s=15,
                   alpha=0.6, zorder=3, label=f'Waypoints ({len(wp_xy)})')

    # GT candidates (sized by norm opinion)
    if all_gt_world:
        gt_arr = np.array(all_gt_world)  # (N, 3): x, y, norm_opinion
        # Deduplicate by position
        _, uniq_idx = np.unique(np.round(gt_arr[:, :2], 3),
                                axis=0, return_index=True)
        gt_uniq = gt_arr[uniq_idx]
        gt_sizes = 20 + np.clip(gt_uniq[:, 2], 0, 1) * 200
        ax.scatter(gt_uniq[:, 0], gt_uniq[:, 1],
                   c='lime', s=gt_sizes, marker='s',
                   edgecolors='darkgreen', linewidths=1,
                   zorder=5, label=f'GT candidates ({len(gt_uniq)})')

    # Predicted candidates (sized by norm score, alpha by confidence)
    if all_pred_world_selected:
        pred_arr = np.array(all_pred_world_selected)  # (N, 4): x,y,conf,score
        pred_sizes = 20 + np.clip(pred_arr[:, 3], 0, 1) * 200
        ax.scatter(pred_arr[:, 0], pred_arr[:, 1],
                   c='red', s=pred_sizes, marker='o',
                   alpha=np.clip(pred_arr[:, 2], 0.25, 1.0).tolist(),
                   edgecolors='darkred', linewidths=0.5,
                   zorder=6, label=f'Predicted ({len(pred_arr)})')

        # Score annotations on top-K predictions
        top_k = min(20, len(pred_arr))
        sorted_idx = np.argsort(-pred_arr[:, 2])[:top_k]
        for i in sorted_idx:
            ax.annotate(
                f'{pred_arr[i, 3]:.3f}',
                (pred_arr[i, 0], pred_arr[i, 1]),
                textcoords='offset points', xytext=(3, 3),
                fontsize=6, color='darkred', alpha=0.8)

    n_gt_u = len(set(tuple(g[:2]) for g in all_gt_world)) \
        if all_gt_world else 0
    n_shown = len(all_pred_world_selected)
    cov_str = f', cov={coverage_rate:.0%}' if coverage_rate else ''
    ax.set_title(
        f'CovDETR Frontier Prediction — Step {fid}  '
        f'({len(wids)} WPs, GT={n_gt_u}, Pred={n_shown}{cov_str})',
        fontsize=12)
    ax.legend(loc='best', fontsize=9)
    ax.set_xlabel('X (m)')
    ax.set_ylabel('Y (m)')
    plt.tight_layout()
    plt.savefig(os.path.join(out_dir, 'summary_frontier_generation_map.png'),
                dpi=150, bbox_inches='tight')
    plt.close()

    print()
    print(f"GT candidates (unique): {n_gt_u}")
    print(f"Predictions total:      {len(all_pred_world)}")
    if coverage_rate is not None:
        print(f"Selected (cov={coverage_rate:.0%}): {len(all_pred_world_selected)}")
    print(f"Saved to {out_dir}/")


# ── CLI ──────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description='Coverage-aware DETR: position + score prediction')
    sub = parser.add_subparsers(dest='command')

    # prepare
    p = sub.add_parser('prepare', help='Pre-compute coverage DETR dataset')
    p.add_argument('--coverage-dir', required=True,
                   help='Coverage dataset directory (with manifest.json)')
    p.add_argument('--out', default='cov_detr_cache',
                   help='Output cache directory')
    p.add_argument('--min-id', type=int, default=None,
                   help='Min frontier ID (inclusive)')
    p.add_argument('--max-id', type=int, default=None,
                   help='Max frontier ID (inclusive)')

    # train
    p = sub.add_parser('train', help='Train coverage DETR model')
    p.add_argument('--data', default='cov_detr_cache')
    p.add_argument('--save-dir', default=None,
                   help='Checkpoint save directory (default: --data dir)')
    p.add_argument('--epochs', type=int, default=200)
    p.add_argument('--batch-size', type=int, default=32)
    p.add_argument('--lr', type=float, default=1e-4)
    p.add_argument('--split-id', type=int, default=1500)
    p.add_argument('--lambda-score', type=float, default=LAMBDA_SCORE)
    p.add_argument('--weight-decay', type=float, default=1e-4)
    p.add_argument('--save-every', type=int, default=50)
    p.add_argument('--min-id', type=int, default=None,
                   help='Min frontier ID for training (inclusive)')
    p.add_argument('--max-id', type=int, default=None,
                   help='Max frontier ID for training (inclusive)')

    # predict
    p = sub.add_parser('predict', help='Predict and visualise')
    p.add_argument('--frontier-id', type=int, required=True)
    p.add_argument('--checkpoint', required=True)
    p.add_argument('--coverage-dir', default=None,
                   help='Coverage dataset dir for GT overlay (optional)')
    p.add_argument('--coverage-rate', type=float, default=None,
                   help='Greedy select predictions by score until '
                        'cumulative score >= this value (e.g. 0.8)')
    p.add_argument('--proximity-disq-m', type=float, default=2.0,
                   help='Disqualify unselected predictions within this '
                        'distance (m) of a selected one (default: 2.0)')
    p.add_argument('--no-wp-plots', action='store_true',
                   help='Skip per-WP BEV visualisation (summary map only)')

    args = parser.parse_args()
    if args.command == 'prepare':
        cmd_prepare(args)
    elif args.command == 'train':
        cmd_train(args)
    elif args.command == 'predict':
        cmd_predict(args)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
